const sb=window.supabase.createClient(BANANA_CONFIG.SUPABASE_URL,BANANA_CONFIG.SUPABASE_ANON_KEY);
const C={};const $=id=>document.getElementById(id);let me=null,profile=null,page="chats",chatUser=null,chatGroup=null,groupOpen=false;
const base=()=>{let p=location.pathname;return p.substring(0,p.lastIndexOf("/")+1)};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const avatar=(p,n,cl="avatar")=>p?`<img class="${cl}" src="${esc(p)}">`:`<div class="${cl}">${esc((n||"?")[0].toUpperCase())}</div>`;
function toast(x){$("toast").textContent=x;$("toast").className="show";setTimeout(()=>$("toast").className="",2400)}
function modal(html){$("modalBox").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()}
function time(t){return t?new Date(t).toLocaleString("fa-IR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):""}
function deviceId(){let k="banana_device_id",v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v}
async function init(){
 const {data:{session}}=await sb.auth.getSession();if(!session){location.href=base()+"login";return}
 me=session.user;
 const ban=await sb.rpc("get_my_ban_status",{p_user_id:me.id,p_device_id:deviceId()});if(ban.data?.blocked){await sb.auth.signOut();location.href=base()+"login";return}
 let r=await sb.from("profiles").select("*").eq("id",me.id).single();if(r.error){await sb.auth.signOut();location.href=base()+"login";return} profile=r.data;
 $("app").classList.remove("hidden");$("topAvatar").outerHTML=avatar(profile.avatar_url,profile.display_name||profile.username,"avatar mini");$("topAvatar").dataset.page="profile";
 if(profile.is_admin)$("adminNav").classList.remove("hidden");loadPage("chats");watch();
}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>loadPage(b.dataset.page));
async function loadPage(p){page=p;document.querySelectorAll(".bottom-nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="chats")await chats();if(p==="search")await search();if(p==="profile")await profilePage();if(p==="settings")await settings();if(p==="notifications")await notifications();if(p==="admin")await admin();if(p==="groups")await groups()}
async function chats(){
 const {data}=await sb.from("messages").select("sender_id,receiver_id,content,created_at").or(`sender_id.eq.${me.id},receiver_id.eq.${me.id}`).eq("is_deleted",false).order("created_at",{ascending:false});
 const seen=new Set(), ids=[];(data||[]).forEach(m=>{let id=m.sender_id===me.id?m.receiver_id:m.sender_id;if(!seen.has(id)){seen.add(id);ids.push({id,m})}});
 let users=[];if(ids.length)users=(await sb.from("profiles").select("id,username,display_name,avatar_url").in("id",ids.map(x=>x.id))).data||[];
 $("content").innerHTML=`<div class="page-head"><h2>چت‌ها</h2><button class="primary" onclick="toggleFab()">＋</button></div><div class="searchbar"><input id="chatFilter" placeholder="جستجوی چت‌های من..."></div><div id="chatList" class="list"></div><button class="fab" id="fab" onclick="toggleFab()">＋</button><div id="fabMenu" class="fab-menu hidden"><button onclick="newChat()">👤 چت جدید</button><button onclick="newGroup()">👥 ساخت گروه</button></div>`;
 const map=new Map(users.map(u=>[u.id,u]));$("chatList").innerHTML=ids.map(x=>{let u=map.get(x.id);return u?`<div class="row chat-row" data-name="${esc(u.username+" "+u.display_name)}" onclick='openUserChat(${JSON.stringify(u)})'>${avatar(u.avatar_url,u.display_name||u.username,"avatar small")}<div class="row-main"><b>${esc(u.display_name||u.username)}</b><small>${esc(x.m.content)}</small></div><time>${time(x.m.created_at)}</time></div>`:""}).join("")||`<div class="empty">هنوز با کسی چت نکرده‌ای.<br>از دکمه جستجو یک نفر را پیدا کن.</div>`;
 $("chatFilter").oninput=e=>document.querySelectorAll(".chat-row").forEach(x=>x.style.display=x.dataset.name.toLowerCase().includes(e.target.value.toLowerCase())?"flex":"none");
}
function toggleFab(){$("fabMenu")?.classList.toggle("hidden")}
async function newChat(){toggleFab();loadPage("search")}
async function newGroup(){toggleFab();const {data}=await sb.rpc("my_group_count");if((data||0)>=3){toast("حداکثر ۳ گروه فعال برای هر کاربر مجاز است.");return}modal(`<div class="modal-head"><h3>ساخت گروه</h3><button class="icon-btn" onclick="closeModal()">×</button></div><label>نام گروه</label><input id="gn" maxlength="50"><label>بیو</label><textarea id="gb" maxlength="300"></textarea><label>عضویت</label><select id="gopen"><option value="true">باز — درخواست عضویت آزاد</option><option value="false">بسته — فقط دعوت</option></select><button class="primary wide" onclick="createGroup()">ساختن</button>`)}
async function createGroup(){const name=$("gn").value.trim();if(!name)return;const {data,error}=await sb.from("groups").insert({owner_id:me.id,name,bio:$("gb").value.trim(),is_open:$("gopen").value==="true"}).select().single();if(error){toast(error.message);return}await sb.from("group_members").insert({group_id:data.id,user_id:me.id,role:"owner",status:"approved"});closeModal();toast("گروه ساخته شد.");openGroup(data)}
async function search(){ $("content").innerHTML=`<div class="page-head"><h2>جستجو</h2></div><div class="searchbar"><input id="q" placeholder="نام کاربری یا نام نمایشی..."><button class="primary" onclick="doSearch()">جستجو</button></div><div id="results" class="list"><div class="empty">برای شروع جستجو کن.</div></div>`}
async function doSearch(){const q=$("q").value.trim();if(!q)return;const users=(await sb.from("profiles").select("id,username,display_name,bio,avatar_url").or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).limit(30)).data||[];const groups=(await sb.from("groups").select("id,name,bio,avatar_url,member_count,is_open").ilike("name",`%${q}%`).limit(30)).data||[];$("results").innerHTML=`${users.map(u=>`<div class="row" onclick='openUserChat(${JSON.stringify(u)})'>${avatar(u.avatar_url,u.display_name||u.username,"avatar small")}<div class="row-main"><b>${esc(u.display_name||u.username)}</b><small>@${esc(u.username)} · ${esc(u.bio||"بدون بیو")}</small></div></div>`).join("")}${groups.map(g=>`<div class="row" onclick='groupInfo(${JSON.stringify(g)})'>${avatar(g.avatar_url,g.name,"avatar small")}<div class="row-main"><b>${esc(g.name)}</b><small>${esc(g.bio||"بدون بیو")} · ${g.member_count||0} عضو</small></div><span>${g.is_open?"باز":"بسته"}</span></div>`).join("")}`||`<div class="empty">چیزی پیدا نشد.</div>`}
async function profilePage(){ $("content").innerHTML=`<div class="page-head"><h2>پروفایل</h2><button class="icon-btn" onclick="loadPage('settings')">⚙</button></div><div class="profile-card">${avatar(profile.avatar_url,profile.display_name||profile.username,"profile-large")}<h2>${esc(profile.display_name||profile.username)}</h2><div class="muted">@${esc(profile.username)}</div><p class="bio">${esc(profile.bio||"هنوز بیویی ثبت نشده.")}</p><button class="primary" onclick="editProfile()">ویرایش پروفایل</button></div>`}
async function editProfile(){modal(`<div class="modal-head"><h3>ویرایش پروفایل</h3><button class="icon-btn" onclick="closeModal()">×</button></div><label>نام نمایشی</label><input id="pd" value="${esc(profile.display_name||"")}"><label>بیو</label><textarea id="pb">${esc(profile.bio||"")}</textarea><label>عکس پروفایل</label><input id="pa" type="file" accept="image/*"><button class="primary wide" onclick="saveProfile()">ذخیره</button>`)}
async function saveProfile(){let url=profile.avatar_url;const f=$("pa").files[0];if(f){if(f.size>3e6){toast("عکس باید کمتر از ۳MB باشد.");return}const path=`avatars/${me.id}-${Date.now()}.${f.name.split(".").pop()}`;let u=await sb.storage.from("media").upload(path,f,{upsert:true});if(u.error){toast(u.error.message);return}url=sb.storage.from("media").getPublicUrl(path).data.publicUrl}let r=await sb.from("profiles").update({display_name:$("pd").value.trim(),bio:$("pb").value.trim(),avatar_url:url}).eq("id",me.id).select().single();if(r.error){toast(r.error.message);return}profile=r.data;closeModal();loadPage("profile");$("topAvatar").outerHTML=avatar(profile.avatar_url,profile.display_name||profile.username,"avatar mini");toast("پروفایل ذخیره شد.")}
async function settings(){$("content").innerHTML=`<div class="page-head"><h2>تنظیمات</h2></div><div class="panel"><div class="setting"><span>👤</span><div><b>پروفایل</b><small>نام، بیو و عکس</small></div><button class="primary right" onclick="editProfile()">ویرایش</button></div><div class="setting"><span>🔑</span><div><b>رمز عبور</b><small>تغییر رمز حساب</small></div><button class="primary right" onclick="changePassword()">تغییر</button></div><div class="setting"><span>🔔</span><div><b>اعلان‌ها</b><small>اعلان‌های داخل برنامه</small></div><button class="switch on right" id="ns" onclick="this.classList.toggle('on')"></button></div><div class="setting"><span>📱</span><div><b>شناسه دستگاه</b><small>${esc(deviceId())}</small></div></div><div class="setting"><span>🚪</span><div><b>خروج از حساب</b></div><button class="danger right" onclick="logout()">خروج</button></div></div>`}
async function changePassword(){modal(`<h3>تغییر رمز</h3><label>رمز جدید</label><input id="np" type="password" minlength="8"><button class="primary wide" onclick="doPassword()">ذخیره</button>`)}
async function doPassword(){const {error}=await sb.auth.updateUser({password:$("np").value});if(error)toast(error.message);else{closeModal();toast("رمز تغییر کرد.")}}
async function logout(){await sb.auth.signOut();location.href=base()+"login"}
async function notifications(){const {data}=await sb.from("notifications").select("*").eq("user_id",me.id).order("created_at",{ascending:false}).limit(100);$("content").innerHTML=`<div class="page-head"><h2>اعلان‌ها</h2><button class="primary" onclick="markNotifications()">خوانده شد</button></div><div class="list">${(data||[]).map(n=>`<div class="row"><div class="row-main"><b>${esc(n.title)}</b><small>${esc(n.body||"")}</small></div><time>${time(n.created_at)}</time></div>`).join("")||'<div class="empty">اعلانی نیست.</div>'}</div>`}
async function markNotifications(){await sb.from("notifications").update({is_read:true}).eq("user_id",me.id);toast("اعلان‌ها خوانده شدند.");loadPage("notifications")}
async function openUserChat(u){chatUser=u;chatGroup=null;renderChat();await refreshMessages()}
async function renderChat(){let el=document.querySelector(".chat");if(!el){el=document.createElement("div");el.className="chat";document.body.appendChild(el)}el.innerHTML=`<div class="chat-head">${avatar(chatUser.avatar_url,chatUser.display_name||chatUser.username,"avatar small")}<div class="row-main"><b>${esc(chatUser.display_name||chatUser.username)}</b><small>@${esc(chatUser.username)}</small></div><button class="close-chat" onclick="closeChat()">×</button></div><div id="chatBody" class="chat-body"></div><form class="chat-input" onsubmit="sendMessage(event)"><textarea id="messageText" rows="1" placeholder="پیام..."></textarea><button class="primary">➤</button></form>`}
async function refreshMessages(){if(!chatUser)return;const {data}=await sb.from("messages").select("*").or(`and(sender_id.eq.${me.id},receiver_id.eq.${chatUser.id}),and(sender_id.eq.${chatUser.id},receiver_id.eq.${me.id})`).eq("is_deleted",false).order("created_at");$("chatBody").innerHTML=(data||[]).map(m=>`<div class="bubble ${m.sender_id===me.id?"mine":""}">${esc(m.content)}<small>${time(m.created_at)}</small></div>`).join("");$("chatBody").scrollTop=$("chatBody").scrollHeight}
async function sendMessage(e){e.preventDefault();const t=$("messageText").value.trim();if(!t)return;const {error}=await sb.from("messages").insert({sender_id:me.id,receiver_id:chatUser.id,content:t});if(error)toast(error.message);else{$("messageText").value="";refreshMessages()}}
function closeChat(){document.querySelector(".chat")?.remove();chatUser=null;chatGroup=null}
async function groupInfo(g){const mem=await sb.from("group_members").select("user_id,role,status").eq("group_id",g.id).eq("status","approved");const isMember=mem.data?.some(x=>x.user_id===me.id);modal(`<div class="join-box"><img src="${esc(g.avatar_url||"")}"><h2>${esc(g.name)}</h2><p>${esc(g.bio||"")}</p><b>${g.member_count||mem.data?.length||0} عضو</b><p>${g.is_open?"عضویت باز است":"عضویت بسته است"}</p>${isMember?`<button class="primary wide" onclick="closeModal();openGroup(${JSON.stringify(g)})">ورود به گروه</button>`:g.is_open?`<button class="primary wide" onclick="requestJoin('${g.id}')">درخواست عضویت</button>`:`<div class="muted">این گروه عضویت بسته دارد.</div>`}</div>`)}
async function requestJoin(id){const {error}=await sb.from("group_join_requests").upsert({group_id:id,user_id:me.id,status:"pending"},{onConflict:"group_id,user_id"});if(error)toast(error.message);else{closeModal();toast("درخواست عضویت ارسال شد.")}}
async function openGroup(g){const m=await sb.from("group_members").select("role,status").eq("group_id",g.id).eq("user_id",me.id).maybeSingle();if(!m.data||m.data.status!=="approved"){groupInfo(g);return}chatGroup=g;chatUser=null;let el=document.querySelector(".chat");if(!el){el=document.createElement("div");el.className="chat";document.body.appendChild(el)}el.innerHTML=`<div class="chat-head">${avatar(g.avatar_url,g.name,"avatar small")}<div class="row-main"><b>${esc(g.name)}</b><small>${g.member_count||0} عضو</small></div>${m.data.role==="owner"||m.data.role==="admin"?`<button class="close-chat" onclick="groupManage(${JSON.stringify(g)})">⚙</button>`:""}<button class="close-chat" onclick="closeChat()">×</button></div><div id="chatBody" class="chat-body"></div><form class="chat-input" onsubmit="sendGroupMessage(event)"><textarea id="messageText" rows="1" placeholder="پیام..."></textarea><button class="primary">➤</button></form>`;refreshGroup()}
async function refreshGroup(){const {data}=await sb.from("group_messages").select("*,profiles(display_name,username)").eq("group_id",chatGroup.id).eq("is_deleted",false).order("created_at");$("chatBody").innerHTML=(data||[]).map(m=>`<div class="bubble ${m.sender_id===me.id?"mine":""}"><b>${esc(m.profiles?.display_name||m.profiles?.username||"کاربر")}</b><br>${esc(m.content)}<small>${time(m.created_at)}</small></div>`).join("");$("chatBody").scrollTop=$("chatBody").scrollHeight}
async function sendGroupMessage(e){e.preventDefault();const t=$("messageText").value.trim();if(!t)return;const {error}=await sb.from("group_messages").insert({group_id:chatGroup.id,sender_id:me.id,content:t});if(error)toast(error.message);else{$("messageText").value="";refreshGroup()}}
async function groupManage(g){const mem=await sb.from("group_members").select("user_id,role,status,profiles(username,display_name)").eq("group_id",g.id).eq("status","approved");const mine=mem.data.find(x=>x.user_id===me.id);modal(`<div class="modal-head"><h3>مدیریت ${esc(g.name)}</h3><button onclick="closeModal()">×</button></div><label>ارسال پیام</label><button class="switch ${g.members_can_message!==false?"on":""}" id="gmSwitch" onclick="this.classList.toggle('on')"></button><div class="member-list">${(mem.data||[]).map(x=>`<div class="row"><div class="row-main"><b>${esc(x.profiles?.display_name||x.profiles?.username)}</b><small>${x.role}</small></div>${mine.role==="owner"&&x.user_id!==me.id?`<button class="primary" onclick="toggleAdmin('${g.id}','${x.user_id}','${x.role}')">${x.role==="admin"?"برکناری":"ادمین"}</button>`:""}</div>`).join("")}</div><button class="danger wide" onclick="deleteGroup('${g.id}')">حذف گروه</button>`)}
async function toggleAdmin(gid,uid,role){const nr=role==="admin"?"member":"admin";const {error}=await sb.rpc("set_group_role",{p_group_id:gid,p_user_id:uid,p_role:nr});if(error)toast(error.message);else{closeModal();toast("نقش تغییر کرد.")}}
async function deleteGroup(id){if(!confirm("گروه حذف شود؟"))return;const {error}=await sb.rpc("delete_group",{p_group_id:id});if(error)toast(error.message);else{closeModal();closeChat();toast("گروه حذف شد.")}}
async function groups(){search()}
async function admin(){if(!profile.is_admin){loadPage("chats");return}$("content").innerHTML=`<div class="page-head"><h2>پنل مدیریت</h2></div><div class="admin-tabs"><button class="active" onclick="adminUsers()">کاربران</button><button onclick="adminBans()">بن‌ها</button><button onclick="adminChats()">چت‌ها</button><button onclick="adminRequests()">درخواست‌ها</button></div><div id="adminArea"></div>`;adminUsers()}
async function adminUsers(){const {data}=await sb.from("profiles").select("*").order("created_at",{ascending:false}).limit(300);$("adminArea").innerHTML=`<div class="list">${(data||[]).map(u=>`<div class="row">${avatar(u.avatar_url,u.display_name||u.username,"avatar small")}<div class="row-main"><b>${esc(u.display_name||u.username)} ${u.is_admin?"♟":""}</b><small>@${esc(u.username)}</small></div><button class="danger" onclick='banUser(${JSON.stringify(u)})'>بن</button></div>`).join("")}</div>`}
async function banUser(u){modal(`<h3>بن ${esc(u.username)}</h3><label>نوع</label><select id="bt"><option value="user">حساب</option><option value="device">دستگاه</option></select><label>تا تاریخ</label><input id="bu" type="datetime-local"><label>دلیل</label><textarea id="br"></textarea><button class="danger wide" onclick="doBan('${u.id}')">ثبت بن</button>`)}
async function doBan(uid){const type=$("bt").value,until=$("bu").value?new Date($("bu").value).toISOString():null,reason=$("br").value.trim();const {error}=await sb.rpc("admin_ban",{p_user_id:uid,p_device_id:type==="device"?deviceId():null,p_type:type,p_until_at:until,p_reason:reason});if(error)toast(error.message);else{closeModal();toast("بن ثبت شد.");adminBans()}}
async function adminBans(){const {data}=await sb.from("bans").select("*,profiles(username,display_name)").order("created_at",{ascending:false}).limit(300);$("adminArea").innerHTML=`<div class="list">${(data||[]).map(b=>`<div class="row"><div class="row-main"><b>${esc(b.profiles?.display_name||b.profiles?.username||b.type)}</b><small>${esc(b.type)} · ${esc(b.reason||"بدون دلیل")} · تا ${b.until_at?time(b.until_at):"نامحدود"}</small></div><button class="primary" onclick="unban('${b.id}')">رفع بن</button></div>`).join("")||'<div class="empty">بن فعالی نیست.</div>'}`}
async function unban(id){const {error}=await sb.rpc("admin_unban",{p_ban_id:id});if(error)toast(error.message);else adminBans()}
async function adminChats(){const {data}=await sb.from("messages").select("*,sender:profiles!messages_sender_id_fkey(username),receiver:profiles!messages_receiver_id_fkey(username)").order("created_at",{ascending:false}).limit(500);$("adminArea").innerHTML=`<div class="list">${(data||[]).map(m=>`<div class="row"><div class="row-main"><b>${esc(m.sender?.username)} → ${esc(m.receiver?.username)}</b><small>${esc(m.content)} · ${time(m.created_at)}</small></div>${m.is_deleted?"حذف شده":`<button class="danger" onclick="deleteMsg('${m.id}')">حذف</button>`}</div>`).join("")||'<div class="empty">پیامی نیست.</div>'}`}
async function deleteMsg(id){const {error}=await sb.rpc("admin_delete_message",{p_message_id:id});if(error)toast(error.message);else adminChats()}
async function adminRequests(){const {data}=await sb.from("group_join_requests").select("*,profiles(username,display_name),groups(name,owner_id)").eq("status","pending").order("created_at",{ascending:false});$("adminArea").innerHTML=`<div class="list">${(data||[]).map(r=>`<div class="row"><div class="row-main"><b>${esc(r.profiles?.username)} → ${esc(r.groups?.name)}</b><small>درخواست عضویت</small></div><button class="primary" onclick="reviewRequest('${r.id}','approved')">قبول</button><button class="danger" onclick="reviewRequest('${r.id}','rejected')">رد</button></div>`).join("")||'<div class="empty">درخواستی نیست.</div>'}`}
async function reviewRequest(id,status){const {error}=await sb.rpc("review_group_request",{p_request_id:id,p_status:status});if(error)toast(error.message);else adminRequests()}
function watch(){sb.channel("banana-live").on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`receiver_id=eq.${me.id}`},()=>{if(chatUser)refreshMessages();loadPage("chats")}).subscribe();sb.channel("banana-notif").on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${me.id}`},()=>{$("notifDot").classList.add("on")}).subscribe()}
init();
